### ISSUE TITLE
No such module JSON

### ISSUE THREAD

**Issue by dmcyk** [vdka/JSON#21]
After adding `Carthage` support it doesn't build anymore in Xcode

Source files of `JSON` target don't know JSON type because `JSONCore` is not imported

**Comment by vdka** [comment]
Ah. So the file https://github.com/vdka/JSON/blob/master/Sources/JSON/CoreExport.swift is seeing you're compiling in Xcode I imagine with JSON as a dependency and isn't doesn't export the import statement.

I will have a look into ways around this, short of finding any I will rejoin the two modules. Thanks for making me aware!

**Comment by vdka** [comment]
Should be fixed by #24
